# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: push

on:
  push:
      # Sequence of patterns matched against refs/heads
      branches:
        # Push events on main branch
        - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          always-auth: true
          token: ${{secrets.PAT}}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci
      - run: npm run build      
      - run: git config --global user.email "lijiuyi1995@outlook.com"
      - run: git config --global user.name "zhao-huo-long"
      - run: git submodule add https://github.com/zhao-huo-long/zhao-huo-long.github.io.git
      - run: rm -rf zhao-huo-long.github.io/calendar
      - run: mv dist zhao-huo-long.github.io/calendar
      - run: |
          cd zhao-huo-long.github.io
          git remote set-url origin https://${{secrets.PAT}}@github.com/zhao-huo-long/zhao-huo-long.github.io.git
          git add .
          git commit -am "update calendar"
          git push
  
